WITH QB_Performance AS (
    SELECT 
        p.SEASON,
        p.SEASON_WEEK,
        p.PLAYER_NAME,
        p.TEAM,
        SUM(p.PASS_YARDS) AS TOTAL_PASS_YARDS,
        SUM(p.PASSING_AIR_YARDS) AS TOTAL_AIR_YARDS,
        SUM(p.PASSING_YARDS_AFTER_CATCH) AS TOTAL_YAC,
        SUM(p.FANTASY_POINTS) AS TOTAL_FANTASY_POINTS,
        COUNT(DISTINCT p.PLAYER_ID) AS GAMES_PLAYED,
        ROUND(SUM(p.PASS_YARDS) / NULLIF(COUNT(DISTINCT p.PLAYER_ID), 0), 2) AS AVG_PASS_YARDS_PER_GAME,
        ROUND(SUM(p.FANTASY_POINTS) / NULLIF(COUNT(DISTINCT p.PLAYER_ID), 0), 2) AS AVG_FANTASY_POINTS_PER_GAME,
        -- Air Yards % (Deep Passer vs. Short Passer Analysis)
        ROUND(SUM(p.PASSING_AIR_YARDS) / NULLIF(SUM(p.PASS_YARDS), 0), 2) AS AIR_YARDS_PERCENTAGE,
        -- Fantasy Efficiency: Fantasy Points per Passing Yard
        ROUND(SUM(p.FANTASY_POINTS) / NULLIF(SUM(p.PASS_YARDS), 0), 2) AS FANTASY_POINTS_PER_YARD
    FROM {{ ref('stg_player_stats_by_game') }} p
    WHERE p.POSITION = 'QB'
    GROUP BY p.SEASON, p.SEASON_WEEK, p.PLAYER_NAME, p.TEAM
)
SELECT 
    SEASON,
    SEASON_WEEK,
    PLAYER_NAME,
    TEAM,
    TOTAL_PASS_YARDS,
    TOTAL_AIR_YARDS,
    TOTAL_YAC,
    TOTAL_FANTASY_POINTS,
    GAMES_PLAYED,
    AVG_PASS_YARDS_PER_GAME,
    AVG_FANTASY_POINTS_PER_GAME,
    AIR_YARDS_PERCENTAGE,
    FANTASY_POINTS_PER_YARD
FROM QB_Performance
ORDER BY TOTAL_FANTASY_POINTS DESC
